[package]
name = "db-sync-tool"
version = "0.1.0"
authors = ["HerbLuo <cloudself.cn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] } # serialize
serde_json = "1.0"
futures = "0.3"
dirs = "3.0"
